# fallatarea2

Este código primero intenta realizar una operación de suma utilizando la cláusula checked. Si se produce un desbordamiento, se capturará la excepción OverflowException y se mostrará un mensaje de error. Luego, se realiza la misma operación utilizando la cláusula unchecked y se muestra el resultado sin revisión de desbordamiento.

![image](https://user-images.githubusercontent.com/73490758/215358708-3a3d96c6-0544-47d5-904e-6ef39660fc7e.png)

![image](https://user-images.githubusercontent.com/73490758/215358699-d8f141ef-cbf2-460b-8132-1284656353f6.png)
